---
name: release

on:
  push:
    branches:
      - main

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          release-count: "0"
          skip-version-file: "true"
          skip-commit: "false"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

    outputs:
      version: ${{ steps.changelog.outputs.tag }}

  build:
    needs: release
    name: Build
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.release.outputs.version }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/checkout@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Allow Gradle
        run: chmod +x ./gradlew

      - name: Show Tag
        run: echo "I'm running on $VERSION"

      - name: Build
        run: ./gradlew build --no-build-cache
